# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'todo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x0btodoPackage\"\r\n\x0bvoidNoParam\"$\n\x08TodoItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\"1\n\tTodoItems\x12$\n\x05items\x18\x01 \x03(\x0b\x32\x15.todoPackage.TodoItem2\xc7\x01\n\x04Todo\x12:\n\ncreateTodo\x12\x15.todoPackage.TodoItem\x1a\x15.todoPackage.TodoItem\x12=\n\treadTodos\x12\x18.todoPackage.voidNoParam\x1a\x16.todoPackage.TodoItems\x12\x44\n\x0freadTodosStream\x12\x18.todoPackage.voidNoParam\x1a\x15.todoPackage.TodoItem0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOIDNOPARAM']._serialized_start=27
  _globals['_VOIDNOPARAM']._serialized_end=40
  _globals['_TODOITEM']._serialized_start=42
  _globals['_TODOITEM']._serialized_end=78
  _globals['_TODOITEMS']._serialized_start=80
  _globals['_TODOITEMS']._serialized_end=129
  _globals['_TODO']._serialized_start=132
  _globals['_TODO']._serialized_end=331
# @@protoc_insertion_point(module_scope)
